package rpg.character;

/**
 * Date: %STABLE_DATE%
 * Version: %VERSION%
 */
public enum EquipamentSlot
{
	UPPER_HEAD, LOWER_HEAD, LEFT_EAR, RIGHT_EAR, NECK, UPPER_BODY, LEFT_GLOVE, LEFT_HAND, LEFT_MIDDLE_FINGER,
	RIGHT_GLOVE, RIGHT_HAND, RIGHT_MIDDLE_FINGER, LOWER_BODY, LEFT_FOOT, RIGHT_FOOT;
}
