package rpg.character;

/**
 * Date: %STABLE_DATE%
 * Version: %VERSION%
 */
public enum EquipamentSlot
{
	UPPERHEAD, LOWERHEAD, LEFTEAR, RIGHTEAR, NECK, UPPERBODY, LEFTGLOVE,
	LEFTHAND, LEFTRING, RIGHTGLOVE, RIGHTHAND, RIGHTRING, LOWERBODY, LEFTFOOT,
	RIGHTFOOT
}
