package rpg.character.attribute.special;

/**
 * @since %STABLE_DATE%
 * @version %VERSION%
 */
public enum SpecialAttribute
{
	MELEE_ATTACK, RANGED_ATTACK, CRITICAL_DAMAGE, FISICAL_ARMOR_PENETRATION, MAGICAL_ARMOR_PENETRATION, PERFECT_DODGE,
	DELAY_AFTER_CAST, HP_BONUS, HP_CONSUMPTION, MP_BONUS, MP_CONSUMPTION;
}
